#!/usr/bin/env bash

for card in cards/*; do
    echo "FS_SG lnN 1.1 - - - -" >> "${card}"
    echo "FS_TT lnN - 1.1 - - -" >> "${card}"
    echo "FS_DY lnN - - 1.1 - -" >> "${card}"
    echo "FS_WJ lnN - - - 1.3 -" >> "${card}"
    echo "FS_WW lnN - - - - 1.1" >> "${card}"
done
